@baseUrl = https://api.event.matheusfelipe.dev/api

@tokenValue = {{authenticate.response.body.token}}
@tokenType = {{authenticate.response.body.token_type}}

@authToken = {{tokenType}} {{tokenValue}}


# @name authenticate
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email":"asdasd@asd.asd",
    "password":"12345678"
}

### PEGAR AS INFORMAÇÕES DO USUARIO LOGADO

# @name commonUser
GET {{baseUrl}}/user
Authorization: Bearer {{tokenValue}}

### Receber Email para recuperar senha
POST {{baseUrl}}/recover-password
Content-Type: application/json

{
  "email":"teste@teste.com"
}

### Resetar senha, digitando uma nova
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "email":"teste@teste.com",
  "token":"asdasdasdasdasd",
  "password":"12345678",
  "password_confirmation":"12345678"
}



### Rota logar como admin

# @name adminUser

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email":"admin@example.com",
    "password":"password"
}


### Rota para fazer cadastro
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "Teste",
  "cpf": "12345",
  "email": "teste@teste.com",
  "password": "12345678",
  "password_confirmation": "12345678"
}

















### Rota pra recuperar os eventos
GET {{baseUrl}}/events
Authorization: {{authToken}}